spring:
  application:
    name: config-server
  cloud:
    config:
      server:
       git:
        uri: https://github.com/ramya9765/config-server
        clone-on-start: true
 
server: 
  port: 8888
